In [20]:
# df.groupby()
# We use the groupby method to split data into multiple groups so that we can apply
# some aggregation functions on it.
import pandas as pd
df=pd.read_csv("grouping_aggregation_practice.csv")
df.groupby("country")["income"].mean()

df.groupby("country")["income"].sum()
df.groupby("country")["income"].count()
df.groupby("country")["income"].max()
df.groupby("country")["income"].min()
df.groupby("country")["income"].std()

# applies multiple aggregate functions
df.groupby("country")["income"].agg(["mean","min","max"])
df.groupby("country")["income"].aggregate(["mean", "min", "max"])

# rename aggregate 

df.groupby("country")["income"].agg(avg_salary="mean", max_salary="max") 
# aggregatre on multiple cols
df.groupby("country").agg({"age":"mean","income":"mean"})

# rename aggregates on multiple cols
df.groupby("country").agg(
    avg_age=("age","mean"),
    avg_salary=("income","mean")
)

           avg_age  avg_salary
country
India    27.000000     50600.0
UK       37.500000     70250.0
USA      33.333333     67000.0

In [6]:
df

      name country  gender  age  income occupation
0     John     USA    Male   28   55000  Developer
1    Alice     USA  Female   32   62000    Teacher
2    Rahul   India    Male   25   48000   Designer
3    Priya   India  Female   29   52000   Engineer
4    David     USA    Male   41   75000    Manager
5     Emma      UK  Female   35   68000     Doctor
6     Aman   India    Male   24   45000  Developer
7     Neha   India  Female   31   58000    Teacher
8   Robert      UK    Male   45   72000    Manager
9     Sara     USA  Female   27   60000   Designer
10   Arjun     USA    Male   38   80000   Engineer
11    Lisa      UK  Female   30   65000     Doctor
12  Daniel   India    Male   26   50000  Developer
13   Kiran     USA  Female   34   70000    Manager
14  Sophia      UK  Female   40   76000   Engineer