In [35]:
# Filtering & Querying Data
# 1) • Boolean Filtering
# We can use for AND, for OR & wrap each condition in parentheses .
import pandas as pd
df=pd.read_csv("global_air_quality_data_10000.csv")

# df[df["PM2.5"]>149]
# df[(df["PM2.5"]>140) & (df["Temperature"]>30) ]

pm_particle=df[(df["PM2.5"]>140) & (df["Temperature"]>37) & (df["Wind Speed"]>6)][["City","Country"]]
pm_particle
# pm_particle.loc[]  # nhi ho payega beacuse ismei lebel ayega 
pm_particle.iloc[0]

# 2) query• Method

df.query("Humidity> 49 and Temperature > 20")
my_coutry="Russia"
df.query("Country==@my_coutry and Humidity> 49 and Temperature > 20")

,City,Country,Date,PM2.5,PM10,NO2,SO2,CO,O3,Temperature,Humidity,Wind Speed
73,Moscow,Russia,2023-01-21,58.66,14.66,72.78,15.02,0.56,56.18,33.71,67.48,9.22
187,Moscow,Russia,2023-06-21,71.61,135.70,61.54,48.20,2.55,125.14,35.80,75.39,5.23
252,Moscow,Russia,2023-03-04,51.69,106.89,89.04,23.04,1.24,116.55,21.02,62.98,2.09
355,Moscow,Russia,2023-12-07,26.18,191.37,44.60,26.09,2.59,179.89,36.96,57.32,0.71
566,Moscow,Russia,2023-11-03,120.76,142.71,63.25,25.63,7.93,20.54,23.27,79.96,4.31
...,...,...,...,...,...,...,...,...,...,...,...,...
9466,Moscow,Russia,2023-11-15,38.62,118.65,99.13,39.48,7.91,116.02,38.11,87.87,6.94
9502,Moscow,Russia,2023-01-15,51.90,73.90,29.51,1.62,1.21,69.31,34.99,49.59,14.78
9540,Moscow,Russia,2023-09-08,66.21,44.49,32.72,17.86,6.15,18.43,38.44,89.97,8.91
9923,Moscow,Russia,2023-06-07,21.78,169.10,68.93,9.10,4.18,38.60,29.56,97.00,12.24
9997,Moscow,Russia,2023-11-26,44.07,143.62,8.41,32.58,0.69,167.68,39.35,53.95,4.56

,City,Country,Date,PM2.5,PM10,NO2,SO2,CO,O3,Temperature,Humidity,Wind Speed
0,Bangkok,Thailand,2023-03-19,86.57,25.19,99.88,30.63,4.46,36.29,17.67,59.35,13.76
1,Istanbul,Turkey,2023-02-16,50.63,97.39,48.14,8.71,3.40,144.16,3.46,67.51,6.36
2,Rio de Janeiro,Brazil,2023-11-13,130.21,57.22,98.51,9.92,0.12,179.31,25.29,29.30,12.87
3,Mumbai,India,2023-03-16,119.70,130.52,10.96,33.03,7.74,38.65,23.15,99.97,7.71
4,Paris,France,2023-04-04,55.20,36.62,76.85,21.85,2.00,67.09,16.02,90.28,14.16
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,Johannesburg,South Africa,2023-09-16,147.85,184.34,90.33,34.93,2.81,191.45,-1.92,65.22,15.48
9996,Berlin,Germany,2023-12-05,12.22,121.49,49.04,5.66,2.10,184.56,-9.81,12.16,10.75
9997,Moscow,Russia,2023-11-26,44.07,143.62,8.41,32.58,0.69,167.68,39.35,53.95,4.56
9998,Berlin,Germany,2023-02-03,67.43,96.79,43.23,29.19,6.01,148.50,26.21,58.54,2.71
9999,Bangkok,Thailand,2023-06-13,16.34,28.80,50.48,21.20,0.49,17.41,2.50,66.05,5.01